language: objective-c
osx_image: xcode10.2

before_install:
  - env
  - locale
  - gem install xcpretty --no-document --quiet
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  - cd Example
  - set -o pipefail

  - xcodebuild clean build -workspace LFPhoneInfo.xcworkspace -scheme LFPhoneInfo-Example -sdk iphonesimulator -configuration Debug | xcpretty -c
  - xcodebuild clean build test -workspace LFPhoneInfo.xcworkspace -scheme LFPhoneInfo-Example -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8,OS=latest" -configuration Debug GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)
